PKG_NAME = lrzsz
PKG_VERS = 0.12.20
PKG_EXT = tar.gz
PKG_NAME_REAL = lrzsz
PKG_DIST_NAME = $(PKG_NAME_REAL)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = https://ohse.de/uwe/releases
PKG_DIST_FILE = $(PKG_NAME_REAL)-$(PKG_VERS).$(PKG_EXT)
PKG_DIR = $(PKG_NAME_REAL)-$(PKG_VERS)

#DEPENDS = cross/openssl

HOMEPAGE = https://ohse.de/uwe/software/lrzsz.html
COMMENT  = free x/y/zmodem implementation
LICENSE  = 

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
