SPK_NAME = nethogs
SPK_VERS = 0.8.7
SPK_REV = 3
SPK_ICON = src/nethogs.png

DEPENDS = cross/$(SPK_NAME)

MAINTAINER = freesmall
DESCRIPTION = NetHogs is a small 'net top' tool. Instead of breaking the traffic down per protocol or per subnet, like most tools do, it groups bandwidth by process
DISPLAY_NAME = nethogs
STARTABLE = no

HOMEPAGE = https://github.com/nethogs
LICENSE = GPL-2.0 license

SPK_COMMANDS = bin/nethogs

include ../../mk/spksrc.spk.mk
